# Generated by Django 2.1.7 on 2019-06-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_contact', models.CharField(max_length=12)),
                ('customer_email', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('city_name', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=8)),
                ('district', models.CharField(default='', max_length=30)),
                ('state_name', models.CharField(max_length=30)),
                ('contry_name', models.CharField(max_length=30)),
                ('due_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_no', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now=True)),
                ('paid_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_discount', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('due_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_system.Customer')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('productorder_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_qty', models.IntegerField()),
                ('paidable_amount', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_system.Orders')),
            ],
            options={
                'db_table': 'productorder',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('product_qty', models.IntegerField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_discount', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_system.Products'),
        ),
    ]
