# Generated by Django 2.1.7 on 2019-06-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='product',
        ),
    ]
