# Generated by Django 2.1.7 on 2019-06-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_system', '0003_remove_productorder_paidable_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
