# Generated by Django 2.1.7 on 2019-06-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_system', '0005_auto_20190614_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(default='', max_length=15),
        ),
    ]
