# Generated by Django 2.1.7 on 2019-06-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_system', '0006_orders_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='product_status',
            field=models.CharField(default='', max_length=15),
        ),
    ]
